
name: Feature Pipeline
on:
# This Definition sets the trigger of the CI pipeline only when the code is pushed to the feature branch
  push:
    branches:
      - feature/**
jobs:
  development_evironment:
    name: Development Enviroment
    environment: 
      name: development
      url: https://github.com
    runs-on: ubuntu-latest    
    steps:
    # Clone of the code
    - uses: actions/checkout@v1
      name: Clone code  
    - name: Linting
      run: echo Linting code.
    - uses: actions/setup-python@v2
      name : Build
    - name: Unit Testing
      run: echo Run Unit testing
    - uses: jannekem/run-python-script-action@v1
      name : Run Code
      with:
      # This is a simple python script that prints in the console the values present inside the function print()
       script: |
              print("Hello World")
              print("Hello Feature 1")